# See https://starship.rs/config

# Wait 100 milliseconds for starship to check files under the current directory.
scan_timeout = 100

[aws]
disabled = true

[directory]
truncation_length = 8

[git_branch]
symbol = ""

[git_status]
ahead = "↑"
behind = "↓"
deleted = "✗"
diverged = "↕"
